spring:
  config:
    name: project2
  datasource:
    url: jdbc:postgresql://localhost:5432/up0401_last
    username: mans
    password: psql_123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Изменено с create-drop на update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  port: 8087